# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EuroBond_Customer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EuroBond_Customer

  target 'EuroBond_CustomerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EuroBond_CustomerUITests' do
    # Pods for testing
  end
  
pod 'SDWebImage'
pod 'Alamofire', '~> 4.4'
pod 'IQKeyboardManagerSwift'
pod 'DPOTPView'
pod 'lottie-ios'
pod 'Toast-Swift', '~> 5.0.1'
pod "ImageSlideshow/Alamofire"
pod 'SlideMenuControllerSwift'
end
