# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'EuroBond_Customer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SDWebImage'
  pod 'Alamofire', '~> 4.4' 
  pod 'IQKeyboardManagerSwift'
  pod 'DPOTPView'
  pod "ImageSlideshow/Alamofire"
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SlideMenuControllerSwift'
  pod 'SRScratchView'
  pod 'QCropper'
  pod 'Kingfisher', '~> 7.0'
  pod 'FirebaseAnalytics'
  pod 'Firebase/Core'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Firebase/Messaging'
  pod 'LanguageManager-iOS'
  pod 'Firebase/Crashlytics'
  pod 'lottie-ios'

  
end
